spring:
  profiles:
    active: dev
  application:
    name: borapagar
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
  security:
    oauth2:
      client:
        registration:
          sigaa:
            client-id: ${SIGAA_CLIENT_ID}
            client-secret: ${SIGAA_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/sigaa"
        provider:
          sigaa:
            userNameAttribute: login
            authorization-uri: https://autenticacao.info.ufrn.br/authz-server/oauth/authorize
            token-uri: https://autenticacao.info.ufrn.br/authz-server/oauth/token
            user-info-uri: https://api.info.ufrn.br/usuario/v1/usuarios/info

springdoc:
  swagger-ui:
    path: /swagger-ui.html

sigaa:
  api-key: ${SIGAA_API_KEY}

frontend:
  url: ${FRONTEND_URL:localhost:8080}
  redirect: ${FRONTEND_URL:localhost:8080}/dashboard
