spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/borapagar'
    username: postgres
    password: password
frontend:
  url: 'http://localhost:5173'
  redirect: '${FRONTEND_URL}/dashboard'
