spring:
  datasource:
    url: 'jdbc:postgresql://${DATABASE_HOST}/${DATABASE_NAME}'
    username: '${DATABASE_USERNAME}'
    password: '${DATABASE_PASSWORD}'
  devtools:
    add-properties: false
  docker:
    compose:
      enabled: false
server:
  address: 0.0.0.0
  port: '8080'
