CREATE TABLE IF NOT EXISTS components
(
    id                        BIGSERIAL PRIMARY KEY,
    total_workload            INTEGER,
    co_requisites             TEXT,
    code                      VARCHAR(255) NOT NULL,
    department                TEXT,
    activity_type_description TEXT,
    mandatory_discipline      BOOLEAN,
    description               TEXT,
    equivalents               TEXT,
    component_id              INTEGER      NOT NULL,
    curriculum_matrix_id      INTEGER,
    activity_type_id          INTEGER,
    component_type_id         INTEGER,
    unit_id                   INTEGER,
    level                     VARCHAR(100),
    name                      VARCHAR(255) NOT NULL,
    num_units                 INTEGER,
    prerequisites             TEXT,
    semester_offer            INTEGER,
    created_at                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                TIMESTAMPTZ DEFAULT NOW(),
    deleted_at                TIMESTAMPTZ
);
