CREATE TABLE IF NOT EXISTS users
(
    id                       BIGSERIAL PRIMARY KEY,
    id_usuario               INTEGER NOT NULL,
    id_discente              BIGINT  NOT NULL,
    id_institucional         BIGINT  NOT NULL,
    id_unidade               INTEGER NOT NULL,
    cpf                      BIGINT  NOT NULL,
    email                    TEXT    NOT NULL,
    name                     TEXT    NOT NULL,
    login                    TEXT    NOT NULL,
    image_url                VARCHAR,
    ativo                    BOOLEAN NOT NULL,
    nome_curso               TEXT    NOT NULL,
    sigla_nivel              TEXT    NOT NULL,
    ano_ingresso             INTEGER NOT NULL,
    periodo_ingresso         INTEGER NOT NULL,
    id_forma_ingresso        INTEGER NOT NULL,
    descricao_forma_ingresso TEXT    NOT NULL,
    id_gestora_academica     INTEGER NOT NULL,
    id_tipo_participante     INTEGER NOT NULL,
    id_instituicao_ensino    INTEGER NOT NULL,
    instituicao_ensino       TEXT    NOT NULL,
    id_polo                  INTEGER NOT NULL,
    polo                     TEXT    NOT NULL,
    created_at               TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at               TIMESTAMPTZ
);
