CREATE TABLE IF NOT EXISTS academic_calendar (
    id BIGSERIAL PRIMARY KEY,
    calendar_id BIGINT,
    is_current BOOLEAN NOT NULL,
    unit_id INTEGER,
    year INTEGER NOT NULL,
    period INTEGER NOT NULL,
    current_vacation_year INTEGER,
    current_vacation_period INTEGER,
    vacation_period_start TIMESTAMPTZ,
    vacation_period_end TIMESTAMPTZ,
    period_start TIMESTAMPTZ,
    period_end TIMESTAMPTZ,
    online_enrollment_start TIMESTAMPTZ,
    online_enrollment_end TIMESTAMPTZ,
    enrollment_processing_start TIMESTAMPTZ,
    enrollment_processing_end TIMESTAMPTZ,
    re_enrollment_start TIMESTAMPTZ,
    re_enrollment_end TIMESTAMPTZ,
    re_enrollment_processing_start TIMESTAMPTZ,
    re_enrollment_processing_end TIMESTAMPTZ,
    extraordinary_enrollment_start TIMESTAMPTZ,
    extraordinary_enrollment_end TIMESTAMPTZ,
    vacation_class_enrollment_start TIMESTAMPTZ,
    vacation_class_enrollment_end TIMESTAMPTZ,
    extraordinary_vacation_enrollment_start TIMESTAMPTZ,
    extraordinary_vacation_enrollment_end TIMESTAMPTZ
    );